// <auto-generated />
namespace BWR.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Create_sp_EmptyDB_Porc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_sp_EmptyDB_Porc));
        
        string IMigrationMetadata.Id
        {
            get { return "202011272350184_Create_sp_EmptyDB_Porc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
