// <auto-generated />
namespace BWR.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_Shaded_Cloumn_For_CompanyCashFlow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Shaded_Cloumn_For_CompanyCashFlow));
        
        string IMigrationMetadata.Id
        {
            get { return "202101031821488_Add_Shaded_Cloumn_For_CompanyCashFlow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
